######################################################################
# Automatically generated by qmake (3.0) ?? ?? 12 14:08:36 2017
######################################################################

QT += widgets
TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
HEADERS += sample.h
SOURCES += sample.cpp
